AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Twishlist:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.twishlist
      Runtime: nodejs6.10
      Events:
        Top:
          Type: Api
          Properties:
            Path: /
            Method: get
        Authenticate:
          Type: Api
          Properties:
            Path: /_auth
            Method: get
        Verify:
          Type: Api
          Properties:
            Path: /_verify
            Method: post
        Register:
          Type: Api
          Properties:
            Path: /_register
            Method: post
        ShowUser:
          Type: Api
          Properties:
            Path: /{screen_name}
            Method: get
        UpdateUser:
          Type: Api
          Properties:
            Path: /_user
            Method: post
      Environment:
        Variables:
          TABLE_NAME: !Ref UsersTable
          IDENTITY_POOL: !Ref IdentityPool
  UsersTable:
    Type: AWS::Serverless::SimpleTable
    PrimaryKey:
      Name: screen_name
      Type: String
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: true
  AuthenticatedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
          - mobileanalytics:PutEvents
          - cognito-sync:*
          - cognito-identity:*
          Resource:
          - "*"
  AuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRoleWithWebIdentity
            Principal:
              Federated:
                - cognito-identity.amazonaws.com
                - api.twitter.com
      ManagedPolicyArns:
        - !Ref AuthenticatedPolicy
  UnauthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRoleWithWebIdentity
            Principal:
              Federated:
                - cognito-identity.amazonaws.com
  RoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated:
          Fn::GetAtt:
            - AuthenticatedRole
            - Arn
        unauthenticated:
          Fn::GetAtt:
            - UnauthenticatedRole
            - Arn
  StaticBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: twishlist-static
